version: "3.3"

services:
  wordpress:
    build: dockerfiles/wordpress
    restart: always
    ports:
      - 8080:80
    links:
      - mysql
    working_dir: /var/www/html
    volumes:
      - ./wp/wp-content/:/var/www/html/wp-content/
    environment:
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress

  mysql:
    image: mariadb #10.3.7-MariaDB ?
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: pa55w0rd
